#!/bin/python3

import os , subprocess , shutil , re
#shutil.copy('/localdisk/data/BPSM/ICA2/pullseq',os.environ['HOME']+'/ICA2')
os.chdir(os.environ['HOME']+'/ICA2')
speciesgive = input('Please enter the organism name you want to search (For example: ascomycete fungi)\n\t')
genenamegive = input('Please enter the gene name you want to search (For example: pyruvate dehydrogenase)\n\t')
#get the input from user

subprocess.call(f"esearch -db protein -query '{speciesgive}[Organism] AND ({genenamegive}[protein name])' | efetch -format fasta > ~/ICA2/sequences.fasta", shell=True)
genefile = open(os.environ['HOME']+'/ICA2/sequences.fasta').read()
genes = genefile.split('\n')
#get a list with each line viewing a item

n = 0
genelist = []
for i in genes :
    if i.startswith('>') :
        gene = i.split('[')[1].split(']')[0]
        genelist.append(gene)
        n +=1
#print(n and ', '.join(genelist))
#show the search result (all the gene name) to the user

allseqerror = genefile.rstrip('\n').split('>')
allseq = allseqerror[1::]
seqdic = {}
for i in allseq :
    genename = i .split('[')[1].split(']')[0]
    seqdic[genename] = i.replace('\n','').split(']')[1]
#make a dictionary whose keys are gene name and values are sequences

if n > 200 :
    answer = input(f"The number of gene searched is {n}, which is more than 200. Do you want to narrow the amount of genes? \n\tPlease type 'yes' or 'no' \n\t").lower()
    while ['yes','no'].count(answer) == 0 :
        answer = input("WRONG ANSWER.\n\t Please type 'yes' or 'no'.")
    if answer == 'yes':
        maxlength = input('Please enter the maxminum length of sequence you want to analysis. (For example 400) \n')
        minlength = input('Please enter the minimum length of sequence you want to analysis. (For example 100) \n')
        subprocess.call(f'./pullseq -i ~/ICA2/sequences.fasta -m {minlength} -a {maxlength} > ~/ICA2/selected.fasta ' , shell = True)
    if answer == 'no' :
        os.chdir(os.environ['HOME']+'/ICA2')
        os.rename('sequences.fasta' , 'selected.fasta')
else:
    os.chdir(os.environ['HOME']+'/ICA2')
    os.rename('sequences.fasta' , 'selected.fasta')
#select the sequences with the order of user's and put all the sequences into one new fasta file

genefile_after = open(os.environ['HOME']+'/ICA2/selected.fasta').read()
genes_after = genefile_after.split('\n')
n_after = 0
genelist_after = []
for i in genes_after :
    if i.startswith('>') :
        gene = i.split('[')[1].split(']')[0]
        genelist_after.append(gene)
        n_after +=1
allname_after = ', '.join(genelist_after)
#get total gene amount and all the gene names for showing them to user later

def show():    
    print('\tMANU\nclustalo\tGeneral purpose multiple sequence alignment program for proteins\nplotcon\t\tPlot conservation of a sequence alignment(but you should do clustalo first)')
    print('pepstats\tCalculate statistics of protein properties\npatmatmotifs\tScan a protein sequence with motifs from the PROSITE database (One sequence each time)')
    print('pepinfo\t\tPlot amino acid properties of a protein sequence in parallel (One sequence each time)')
show()
choice = input("What protein sequence analysis do you want to do. Here are the manu of the protein sequence analysis? (If you want to quit from this program, just print 'exit')\n\t").lower()
#show all the functions to user and get the choice

def namechange(name,namelist,file):
    list = file.split('\n')
    if namelist.count(name) > 1 :
        numberlist = []
        for i in list :
            if i.startswith('>') :
                if name == i.split('[')[1].split(']')[0] :
                    numberlist.append(i.split(' ')[0].split('>')[1])
        print(set(numberlist))
        name = input(f'There are more than one sequences whose name is {name}. Please select the session number from this list\n\t')
    else :
        for i in list :
            if i.startswith('>') :
                if name == i.split('[')[1].split(']')[0] :
                    name = i.split(' ')[0].split('>')[1]
    return name

def findhit(filename) :
    file = open(filename).read().split('#')
    number = 0
    for i in file :
        if i.startswith(' HitCount') :
            number = i.split(' ')[-1].rstrip()
    return number
        


while choice != 'exit' :
    if choice == 'clustalo' :
        subprocess.call('clustalo -t Protein -i ~/ICA2/selected.fasta -o ~/ICA2/clustalo_analysis.msf --outfmt msf ' , shell = True )
        show()
        choice = input("The result of clustalo analysis has been put in ICA2. What else do you want to do? \n(If you want to quit, just print 'exit')\n\t").lower()
        
    if choice == 'plotcon' :
        subprocess.call('plotcon -sformat msf ~/ICA2/clustalo_analysis.msf -graph png' , shell = True )
        show()
        choice = input("The picture of plotcon analysis has been put in ICA2. What else do you want to do? \n(If you want to quit, just print 'exit')\n\t").lower()
        
    if choice == 'pepstats' :
        subprocess.call('pepstats -sequence ~/ICA2/selected.fasta -outfile ~/ICA2/statistics_analysis' , shell = True )
        show()
        choice = input("The result of pepstats analysis has been put in ICA2. What else do you want to do? \n(If you want to quit, just print 'exit')\n\t" ).lower()
        
    if choice == 'pepinfo' :
        print(f'After selection, there are {n_after} sequences left. The gene names are {allname_after} ')
        name = input('Please enter choose one gene name ,from the list above, you want to analysis\n\t')
        if allname_after.count(name) > 1 :
            name_session = namechange(name,allname_after,genefile_after)
            with open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w') :
                open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w').write(f'{name_session}')
            os.chdir(os.environ['HOME'] + '/ICA2')
            subprocess.call(f'./pullseq -i ~/ICA2/selected.fasta -n ~/ICA2/{name_session} > ~/ICA2/{name_session}.fasta | pepinfo -sequence ~/ICA2/{name_session}.fasta -graph png -outfile ~/ICA2/{name_session}_pepinfo_analysis' , shell=True )
        else :
            name_session = namechange(name,allname_after,genefile_after)
            with open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w') :
                open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w').write(f'{name_session}')      
            os.chdir(os.environ['HOME'] + '/ICA2')
            subprocess.call(f'./pullseq -i ~/ICA2/selected.fasta -n ~/ICA2/{name_session} > ~/ICA2/{name_session}.fasta | pepinfo -sequence ~/ICA2/{name_session}.fasta -graph png -outfile ~/ICA2/{name_session}_pepinfo_analysis' , shell=True )
        show()
        choice = input("The picture of pepinfo analysis has been put in ICA2. (The file name has changed into its session number {name_session}) What else do you want to do? \n(If you want to quit, just print 'exit')\n\t").lower()
        
    if choice == 'patmatmotifs' :
        print(f'After selection, there are {n_after} sequences left. The gene names are {allname_after} ')
        name = input('Please enter choose one gene name ,from the list above, you want to analysis\n\t')
        if allname_after.count(name) > 1 :
            name_session = namechange(name,allname_after,genefile_after)
            with open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w') :
                open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w').write(f'{name_session}')
            os.chdir(os.environ['HOME'] + '/ICA2')
            subprocess.call(f'./pullseq -i ~/ICA2/selected.fasta -n ~/ICA2/{name_session} > ~/ICA2/{name_session}.fasta | patmatmotifs -sequence ~/ICA2/{name_session}.fasta -outfile ~/ICA2/{name_session}_motifs_analysis' , shell = True)
        else :
            name_session = namechange(name,allname_after,genefile_after)
            with open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w') :
                open(os.environ['HOME'] + f'/ICA2/{name_session}' ,'w').write(f'{name_session}')      
            os.chdir(os.environ['HOME'] + '/ICA2')
            subprocess.call(f'./pullseq -i ~/ICA2/selected.fasta -n ~/ICA2/{name_session} > ~/ICA2/{name_session}.fasta | patmatmotifs -sequence ~/ICA2/{name_session}.fasta -outfile ~/ICA2/{name_session}_motifs_analysis' , shell = True)
        filenameX =(os.environ['HOME'] + f'/ICA2/{name_session}_motifs_analysis') 
        number = findhit(filenameX)
        print(f'\nUsing PROSITE database, finding {number} motif(s) in {name_session}\n')
        show()
        choice = input("The result of patmatmotifs analysis has been put in ICA2. (The file name has changed into its session number {name_session}) What else do you want to do? \n(If you want to quit, just print 'exit')\n\t").lower()
print('THANK YOU for using this program, Have a nice day!')
exit()

#debug!!!!!!!!!!!!!!!!